'use strict';
const fs=require('node:fs'),path=require('node:path'),{spawnSync}=require('node:child_process');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),out=path.join(__dirname,'output'),media=path.join(root,'docs/media');
fs.mkdirSync(out,{recursive:true});fs.mkdirSync(media,{recursive:true});
const url=process.env.ZHIYAN_URL||'http://127.0.0.1:61321/';
const fast=process.argv.includes('--check'),wait=ms=>new Promise(r=>setTimeout(r,fast?Math.min(ms,160):ms));
const stamp=ms=>{ms=Math.max(0,Math.round(ms));return [Math.floor(ms/3600000),Math.floor(ms/60000)%60,Math.floor(ms/1000)%60].map(n=>String(n).padStart(2,'0')).join(':')+'.'+String(ms%1000).padStart(3,'0')};
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.BROWSER_PATH?{executablePath:process.env.BROWSER_PATH}:{})});
 const context=await browser.newContext({viewport:{width:1920,height:1080},deviceScaleFactor:1,...(!fast?{recordVideo:{dir:out,size:{width:1920,height:1080}}}:{})});
 const page=await context.newPage(),errors=[],chapters=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.setContent(fs.readFileSync(path.join(__dirname,'stage.html'),'utf8').replaceAll('__BASE__',url));
 const frame=page.frames().find(f=>f.url().includes('index.html'));
 await frame.waitForFunction(()=>window.YanceApp&&window.ZhiyanInference&&window.yanceTown?.width>0);
 await Promise.all([page.evaluate(()=>document.fonts.ready),frame.evaluate(()=>document.fonts.ready)]);
 await frame.evaluate(()=>{yanceTown.setPlaying(false)});
 const started=Date.now();
 const cue=async(title,cn,en)=>{if(chapters.length)chapters.at(-1).endMs=Date.now()-started;chapters.push({title,cn,en,startMs:Date.now()-started});await page.evaluate(({title,cn,en,n})=>{document.querySelector('#focus').style.opacity=0;document.querySelector('#chapter').textContent=title;document.querySelector('#cn').textContent=cn;document.querySelector('#en').textContent=en;document.querySelector('#bar').style.width=Math.min(100,n*5)+'%'},{title,cn,en,n:chapters.length});console.log('SHOT '+title)};
 const fade=async action=>{await page.evaluate(()=>{document.querySelector('#screen').style.opacity='.18';document.querySelector('#focus').style.opacity=0});await wait(230);await action();await page.evaluate(()=>document.querySelector('#screen').style.opacity=1);await wait(250)};
 const scroll=async selector=>{await frame.locator(selector).first().evaluate(el=>el.scrollIntoView({behavior:'smooth',block:'start'}));await page.waitForTimeout(700)};
 const click=async s=>{await frame.locator(s).first().click();await wait(200)};
 const focus=async selector=>{const box=await frame.locator(selector).first().evaluate(el=>{const r=el.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height}});await page.evaluate(b=>{const e=document.querySelector('#focus');Object.assign(e.style,{left:100+b.x*1.19444+'px',top:105+b.y*1.19444+'px',width:b.w*1.19444+'px',height:b.h*1.19444+'px',opacity:1})},box)};
 const snap=async name=>page.screenshot({path:path.join(out,name+'.png')});
 const builder=async open=>{if(await frame.locator('.scene-display').evaluate(e=>e.open)!==open)await click('.scene-display summary')};
 await cue('01 / WHY','一个方案上线前，能否先看见它会改变谁？','Before a strategy goes live, can we see who it changes?');
 await page.screenshot({path:path.join(root,'docs/assets/demo-cover.png')});await wait(4500);
 await page.evaluate(()=>document.querySelector('#card').style.opacity=0);await wait(400);await page.evaluate(()=>document.querySelector('#card').style.display='none');
 await cue('01 / THE SYSTEM','智演，把策略、人群与资源约束放进同一场景。','ZHIYAN brings strategies, people and resource constraints into one scene.');
 await fade(()=>scroll('.intro'));await snap('01-workspace');await wait(5000);
 await cue('02 / BUSINESS QUESTION','全客群优惠，还是会员定向？先比较，再试点。','Broad discounts or member offers? Compare first, then pilot.');
 await scroll('.strategy-workspace');await focus('#scheme-options');await wait(4700);
 await cue('03 / SCENARIO','输入背景，确认地图、客流与设施识别结果。','Describe the setting. Review the map, traffic and facilities.');
 await fade(async()=>{await scroll('.world-panel');await builder(true)});
 await frame.locator('#scene-context').fill('周末，滨水集市集中举办促销活动。');await frame.locator('#scene-context').blur();
 await frame.waitForFunction(()=>yanceTown.options.flow==='peak'&&yanceTown.options.facilities==='active');
 await frame.locator('#scene-light').selectOption('day');await snap('02-scenario');await wait(4700);
 await cue('04 / SPATIAL CONTEXT','地图切换会重建道路、设施和人物路线。','Maps change streets, facilities and participant routes.');
 await click('[data-map="merchant-neighborhood"]');await wait(1200);await click('[data-map="merchant-riverside"]');await builder(false);await frame.evaluate(()=>{yanceTown.setProgress(.16);yanceTown.draw()});await page.evaluate(()=>document.querySelector('#focus').style.opacity=0);await wait(4500);
 await cue('05 / PEOPLE','每位人物都有画像、当前位置与目的地。','Each participant has a profile, a position and a destination.');
 await scroll('.observer');await frame.locator('#visitor-select').selectOption('1');await focus('.observer');await wait(4500);
 await cue('05 / FOLLOW','高亮路径与跟随镜头，让行为可以被观察。','Highlighted routes and a following camera make behavior visible.');
 await click('#follow-observer');await fade(()=>scroll('.world-canvas'));await frame.evaluate(()=>yanceTown.setPlaying(true));await wait(5000);await frame.evaluate(()=>{yanceTown.setPlaying(false);yanceTown.setFollowing(false);yanceTown.resetCamera()});
 await cue('06 / MULTI-MODEL','多家云端与本地模型：统一路由，自由分配。','Cloud and local model families: one registry, flexible assignment.');
 await fade(()=>click('#models-open'));await frame.locator('#model-search').fill('DeepSeek');await frame.locator('#model-groups select').first().selectOption('deepseek-chat');await wait(1200);await frame.locator('#model-search').fill('Claude');await frame.locator('#model-groups select').nth(1).selectOption('claude-sonnet');await wait(1200);await frame.locator('#model-search').fill('');await frame.locator('#model-catalog-status').scrollIntoViewIfNeeded();await snap('03-models');await wait(2800);
 await cue('06 / CONNECTION','本地或云端，使用服务端配置；未连接不会冒充成功。','Local or cloud, configured server-side. Unconnected models stay unverified.');
 await click('#model-connect');await frame.waitForFunction(()=>document.querySelector('#gateway-status').textContent.includes('网关已连接'));await focus('#gateway-status');await wait(4300);
 await cue('06 / EXPLANATION','解释有来源；业务指标与生成文本分开呈现。','Explanations show their source, separately from business metrics.');
 await frame.locator('#actor-model').scrollIntoViewIfNeeded();await frame.locator('#actor-model').selectOption('llama-local');await wait(1700);await frame.locator('#actor-model').selectOption('rules');await click('#model-ask');await frame.locator('#model-answer').scrollIntoViewIfNeeded();await focus('#model-answer');await wait(4000);await click('#models-dialog [data-close]');
 await cue('07 / STRATEGY','换一种行动，保留同一组比较条件。','Change the action while keeping comparison conditions fixed.');
 await fade(()=>scroll('.strategy-workspace'));await click('[data-scheme="member"]');await focus('#effect-metrics');await wait(4200);
 await cue('07 / CUSTOM','复制并命名自己的策略，原方案仍作参照。','Create a named strategy while preserving the original alternatives.');
 await click('[data-scheme="custom"]');await frame.locator('#custom-name').fill('周末会员试点');await frame.locator('#custom-name').blur();await focus('#custom-identity');await wait(4200);
 await cue('08 / COMPARISON','同时比较转化率、贡献毛利和优惠投入。','Compare conversion, contribution margin and incentive spend together.');
 await fade(async()=>{await click('#tab-comparison');await scroll('#view-comparison')});await page.evaluate(()=>document.querySelector('#focus').style.opacity=0);await snap('04-results');await wait(5400);
 await cue('08 / EXPLAINABILITY','看清主要人群、资源边界，再安排真实验证。','Identify affected groups and resource limits before real-world validation.');
 await scroll('#insights');await snap('05-insights');await wait(4700);
 await cue('09 / DELIVERY','保存研究与报告，让讨论变成可复用的交付。','Save the study and report so the analysis can be reused.');
 await fade(()=>click('[data-action="report"]'));await frame.locator('#report-name').fill('智演 · 周末会员试点');await wait(2000);await frame.locator('#report-body').evaluate(e=>e.scrollIntoView({behavior:'smooth'}));await wait(3200);await click('#report-dialog [data-close]');
 await cue('10 / POLICYLAB','公共服务：比较网点、开放时段与居民可达性。','Public services: compare locations, opening hours and accessibility.');
 await fade(async()=>{await click('[data-module="public"]');await scroll('.world-panel');await builder(true);await click('[data-map="public-transit"]');await frame.locator('#scene-light').selectOption('day');await builder(false)});await wait(4500);
 await cue('10 / GROWTHLAB','企业增长：比较引导路径、激活与留存。','Growth: compare onboarding paths, activation and retention.');
 await fade(async()=>{await click('[data-module="growth"]');await scroll('.world-panel');await builder(true);await click('[data-map="growth-expo"]');await builder(false)});await snap('06-growth');await wait(4500);
 await cue('11 / THE DIRECTION','目标：大规模多智能体预实验，更快、更省、更可解释。','Our goal: large-scale multi-agent pre-experiments that are faster, leaner and explainable.');
 await page.evaluate(()=>{const e=document.querySelector('#card');e.style.display='flex';e.style.opacity=1;e.querySelector('h1').textContent='更快 · 更省 · 更可解释';e.querySelector('h1').style.fontSize='78px';e.querySelector('p').textContent='Faster exploration. Leaner experiments. Explainable decisions.';e.querySelector('p').style.fontSize='30px';e.querySelector('small').textContent='设计目标 · 当前版本为规则预演与逐人物模型接口 / Design goal, not a benchmark claim.'});await wait(6000);
 await cue('12 / NEXT STEP','从预演中筛选方向，在真实实验中验证价值。','Find a direction in simulation. Validate its value in a real experiment.');
 await page.evaluate(()=>{const e=document.querySelector('#card');e.querySelector('h1').textContent='智演 ZHIYAN';e.querySelector('p').textContent='从更清楚的问题，走向更好的决策。';e.querySelector('small').textContent='kzczc.github.io/zhiyan-decision-studio · Calibrate. Rehearse. Validate.'});await wait(4500);
 chapters.at(-1).endMs=Date.now()-started;await snap('07-end');
 if(errors.length)throw Error(errors.join('\n'));
 const video=page.video(),videoPath=video?await video.path():null;await context.close();await browser.close();
 if(!fast){fs.copyFileSync(videoPath,path.join(out,'zhiyan-demo-bilingual.webm'));const executable=process.env.FFMPEG_PATH;if(executable){const converted=spawnSync(executable,['-y','-i',path.join(out,'zhiyan-demo-bilingual.webm'),'-c:v','libx264','-crf','17','-preset','medium','-pix_fmt','yuv420p','-movflags','+faststart',path.join(media,'zhiyan-demo.mp4')],{encoding:'utf8'});if(converted.status!==0)throw Error(converted.stderr.slice(-2000));}}
 const vtt=['WEBVTT',''];for(const c of chapters)vtt.push(stamp(c.startMs)+' --> '+stamp(c.endMs)+'\n'+c.cn+'\n'+c.en+'\n');
 if(!fast)fs.writeFileSync(path.join(media,'zhiyan-demo.vtt'),vtt.join('\n'));fs.writeFileSync(path.join(out,fast?'check-chapters.json':'chapters.json'),JSON.stringify({durationMs:Date.now()-started,chapters,errors},null,2));
 console.log(JSON.stringify({ok:true,dryRun:fast,chapters:chapters.length,durationMs:Date.now()-started,output:media}));
})().catch(error=>{console.error(error);process.exit(1)});
